accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from accounts.views import signup


urlpatterns = [
    path("signup/", signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

# from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    AccountCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="account_create",
    ),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="categories_list",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="categories_create",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# from django.core.validators import RegexValidator


# alphanumeric = RegexValidator(
#     r"^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed."
# )
# validators=[alphanumeric]

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()

    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from venv import create
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from receipts.models import Account, ExpenseCategory, Receipt

# receipts--------------
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "category",
        "account",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

#this filters out fields for the current to see only their receipts/tasks
    # def get_form(self, *args, **kwargs):
    #         form = super(ReceiptCreateView, self).get_form(*args, **kwargs)
    #         form.fields["category"].queryset = ExpenseCategory.objects.filter(
    #             owner=self.request.user
    #         )
    #         form.fields["account"].queryset = Account.objects.filter(
    #             owner=self.request.user)
    #         return form


# expenses-------------
class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("categories_list")


# account--------------
class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("accounts_list")

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/pretty.css' %}">
    <title>Money Things</title>
</head>
<body>  
    <header>
        <nav class="navbar">            
            {%if user.is_authenticated %}
                <a href="{% url 'home' %}">Receipts</a>
                <a href="{% url 'receipt_create' %}">New Receipt</a>
                <a href="{% url 'accounts_list' %}">Accounts</a>
                <a href="{% url 'account_create' %}">New Account</a>
                <a href="{% url 'categories_list' %}">Expense Categories</a>
                <a href="{% url 'categories_create' %}">New Expense Category</a>                
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                   <a href="{% url 'login' %}">Login</a>
                    <a href="{% url 'signup' %}">Sign up!</a>
            {% endif %}                     
        </nav>
    </header>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
</body>
</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}
{% block content %}
<h1>List of Accounts</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Receipts</th>
        </tr>
    </thead>
    <tbody>
    {% for account in account_list %}
        <tr>
            <td> {{ account.name }}</td>
            <td> {{ account.number }}</td>
            <td> {{ account.receipts.all|length }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1>Create Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}
{% block content %}
<h1 class='center'>List of Categories</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Receipts</th>
        </tr>
    </thead>
    <tbody>
    {% for category in expensecategory_list %}
        <tr>
            <td> {{ category.name }}</td>
            <td> {{ category.receipts.all|length }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<table>
    <h1 class='center'>Receipts</h1>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tb>
    {% for item in receipt_list %}
        <tr>
            <td> {{ item.vendor }}</td>
            <td> {{ item.total }}</td>
            <td> {{ item.tax }}</td>
            <td> {{ item.date|date:"m-d-Y" }}</td>
            <td> {{ item.category.name }}</td>
            <td> {{ item.account.name }}</td>
        </tr>
    {% endfor %}
    </tb>
</table>
{% endblock content %}